//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace dbApplication
{
    using System;
    using System.Collections.ObjectModel;
    
    public partial class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Surname { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> Position { get; set; }
        public Nullable<int> WorkingTime { get; set; }
    
        public virtual Gender Gender1 { get; set; }
        public virtual Position Position1 { get; set; }
        public virtual WorkingTime WorkingTime1 { get; set; }
    }
}
